package com.fantasystep.annotation;

public enum ControlType {
	TEXTBOX, TEXTAREA, PASSWORD, CHECKBOX, TRISTATE, DROPDOWN, TREEDROPDOWN, RADIO, CALENDAR, DATEOFBIRTH, FILEUPLOAD, MEMBERLIST, DYNAMICRELATION, LABEL, JSON_TEXTAREA
}
